<a href="https://colab.research.google.com/github/Nisa-a/EDI-Dashboard/blob/main/ProcessedStudentData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing pandas library.
import pandas as pd
# Importing python package to visualise the variables.
import plotly.express as px

In [ ]:
# Loading dataset into a data frame.
df = pd.read_csv('/content/EDI Dummy data.csv')

In [ ]:
# View the first 5 rows.
df.head()

,STUDENTYEARMODULE,SID,NUMHUS,COURSETITLE,MODULENAME,CREDITS,LEVEL,SEMESTER,AGEONENTRY,SEX,...,GREATSTARTACCESS,BURSARY,CLASSIFICATION,MABSEQ,ASSTYPECODE,ASSTYPENAME,ASSPERC,HASMC,ACCEPTEDMC,MODULEGRADE
0,"A__A8RSWA]71Z""6)5?M5U-",1.910000e+12,1,BSc Psychology FT,Individual Differences,20,4,SEM1,18,Female,...,Other students,Other students,02:01,1,CWK,Coursework,0.5,0,0,62.29
1,"A__A8RSWA]71Z""6)5?M5U-",1.910000e+12,1,BSc Psychology FT,Individual Differences,20,4,SEM1,18,Female,...,Other students,Other students,02:01,2,EXC,Examination - closed book,0.5,0,0,65.10
2,A-A@&M]ZHTX&TG;)H.6PX*,1.910000e+12,1,BSc Psychology FT,Individual Differences,20,4,SEM1,18,Female,...,Other students,Other students,02:01,1,CWK,Coursework,0.5,0,0,59.70
3,A-A@&M]ZHTX&TG;)H.6PX*,1.910000e+12,1,BSc Psychology FT,Individual Differences,20,4,SEM1,18,Female,...,Other students,Other students,02:01,2,EXC,Examination - closed book,0.5,0,0,69.09
4,"A-P,&^E3(;1GXP-&,\Y5^,",1.910000e+12,1,BSc Cognitive and Clinical Neuroscience FT,Cognitive Psychology,20,4,SEM1,21,Female,...,Other low income students,Other low income students,02:01,1,CWK,Coursework,0.4,0,0,61.90

In [ ]:
# View the data types.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2528 entries, 0 to 2527
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   STUDENTYEARMODULE   2528 non-null   object
 1   SID                 2528 non-null   float64
 2   NUMHUS              2528 non-null   int64
 3   COURSETITLE         2528 non-null   object
 4   MODULENAME          2528 non-null   object
 5   CREDITS             2528 non-null   int64
 6   LEVEL               2528 non-null   int64
 7   SEMESTER            2528 non-null   object
 8   AGEONENTRY          2528 non-null   int64
 9   SEX                 2528 non-null   object
 10  ETHNICITY           2528 non-null   object
 11  ETHNICITYDETAILED   2528 non-null   object
 12  DISABLETYPE         2528 non-null   object
 13  CARELEAVER          2528 non-null   object
 14  IMDQUINTILE         2528 non-null   object
 15  ACCOMMODATIONTYPE   2528 non-null   object
 16  COMMUTELENGTH       2528 non-null   object
 17  OFSENTQUALGRPCODE   2528 non-null   int64
 18  OFSENTQUALGRPLABEL  2528 non-null   object
 19  HESATARIFFGRPCODE   2528 non-null   object
 20  HESATARIFFGRPLABEL  2528 non-null   object
 21  TARIFFPOINTS        2528 non-null   int64
 22  STATEMARKERLABEL    2528 non-null   object
 23  SCHOLARSHIPANY      2528 non-null   object
 24  GREATSTARTACCESS    2528 non-null   object
 25  BURSARY             2528 non-null   object
 26  CLASSIFICATION      2528 non-null   object
 27  MABSEQ              2528 non-null   int64
 28  ASSTYPECODE         2528 non-null   object
 29  ASSTYPENAME         2528 non-null   object
 30  ASSPERC             2528 non-null   float64
 31  HASMC               2528 non-null   int64
 32  ACCEPTEDMC          2528 non-null   int64
 33  MODULEGRADE         2528 non-null   float64
dtypes: float64(3), int64(9), object(22)
memory usage: 671.6+ KB

In [ ]:
# Removing unnecessary variables.
df.drop(['STUDENTYEARMODULE', 'SID','NUMHUS','CREDITS','OFSENTQUALGRPCODE','HESATARIFFGRPCODE','HESATARIFFGRPLABEL','STATEMARKERLABEL','MABSEQ','ASSTYPECODE','HASMC','ACCEPTEDMC'], axis= 1, inplace= True)

In [ ]:
# view the dimensions of the data frame.
df.shape

(2528, 22)

In [ ]:
# View basic descriptive statistics for numeric variables.
df.describe()

        LEVEL   AGEONENTRY  TARIFFPOINTS      ASSPERC  MODULEGRADE
count  2528.0  2528.000000   2528.000000  2528.000000  2528.000000
mean      4.0    19.194620     96.355617     0.462421    60.318192
std       0.0     3.687015     39.827215     0.157305     9.530441
min       4.0    18.000000      0.000000     0.200000    40.000000
25%       4.0    18.000000     88.000000     0.400000    53.650000
50%       4.0    18.000000     96.000000     0.500000    60.570000
75%       4.0    19.000000    112.500000     0.500000    66.992500
max       4.0    56.000000    182.000000     0.800000    80.000000

In [ ]:
# View basic descriptive statistics for categorical variables.
df.describe(include='object')

,COURSETITLE,MODULENAME,SEMESTER,SEX,ETHNICITY,ETHNICITYDETAILED,DISABLETYPE,CARELEAVER,IMDQUINTILE,ACCOMMODATIONTYPE,COMMUTELENGTH,OFSENTQUALGRPLABEL,SCHOLARSHIPANY,GREATSTARTACCESS,BURSARY,CLASSIFICATION,ASSTYPENAME
count,2528,2528,2528,2528,2528,2528,2528,2528,2528,2528,2528,2528,2528,2528,2528,2528,2528
unique,3,6,2,2,5,14,5,3,6,4,8,9,2,3,3,3,5
top,BSc Psychology FT,Introduction to Psychological Research Methods,SEM2,Female,Asian,"White - English, Scottish, Welsh, Northern Iri...",Not disabled,Not a care leaver,Quintile 2,Commuter,6-10 miles,A-levels (CDD or higher),Not a scholarship student,Other students,Other students,02:01,Examination - closed book
freq,1663,570,1336,2314,1205,845,2321,1977,919,1709,964,913,2476,1552,1539,1545,1169

In [ ]:
from numpy import diff
# View missing values in each variable.
df.isnull().sum()

COURSETITLE           0
MODULENAME            0
LEVEL                 0
SEMESTER              0
AGEONENTRY            0
SEX                   0
ETHNICITY             0
ETHNICITYDETAILED     0
DISABLETYPE           0
CARELEAVER            0
IMDQUINTILE           0
ACCOMMODATIONTYPE     0
COMMUTELENGTH         0
OFSENTQUALGRPLABEL    0
TARIFFPOINTS          0
SCHOLARSHIPANY        0
GREATSTARTACCESS      0
BURSARY               0
CLASSIFICATION        0
ASSTYPENAME           0
ASSPERC               0
MODULEGRADE           0
dtype: int64

In [ ]:
# View the unique values.
df['ETHNICITY'].unique()

array(['Asian', 'White', 'Black', 'Other', 'Not known'], dtype=object)

In [ ]:
# View the unique values.
df['ETHNICITYDETAILED'].unique()

array(['Asian - Bangladeshi or Bangladeshi British',
       'White - English, Scottish, Welsh, Northern Irish or British',
       'Black - African or African British', 'Any other Asian background',
       'Asian - Pakistani or Pakistani British',
       'Any other Mixed or Multiple ethnic background', 'Arab',
       'Asian - Indian or Indian British',
       'Mixed or multiple ethnic groups - White or White British and Asian or Asian British',
       'Any other ethnic background', 'Not known',
       'Mixed or multiple ethnic groups - White or White British and Black Caribbean or Black Caribbean British',
       'Black - Caribbean or Caribbean British',
       'Mixed or multiple ethnic groups - White or White British and Black African or Black African British'],
      dtype=object)

In [ ]:
# View the unique values.
df['IMDQUINTILE'].unique()

array(['Quintile 2', 'Quintile 3', 'Quintile 4', 'Quintile 5',
       'Quintile 1', 'Unknown / non-UK'], dtype=object)

In [ ]:
# View the unique values.
df['OFSENTQUALGRPLABEL'].unique()

array(['A-levels (CDD or higher)',
       'A-levels (DDD or lower), other level 3 qualification (105 tariff points or higher) or two A-levels and one BTEC',
       'A-levels (ABB or higher)',
       'A-levels (BCC or higher) or international baccalaureate',
       'BTECs (at least DDM), or one A-level and two BTECs',
       'Access or foundation courses, or other level 3 qualification (66 tariff points or higher)',
       'HE-level', 'BTECs (lower than DDM)',
       'None, unknown or other entry qualifications'], dtype=object)

In [ ]:
# View the unique values.
df['HESATARIFFGRPLABEL'].unique()

array(['66 - 80 points', '91 - 105 points',
       'Not in the standard tariff population', '116+ points',
       '81 - 90 points', '106 - 115 points',
       'Not known or zero tariff points', '41 - 65 points',
       'Less than 41 points'], dtype=object)

In [ ]:
# View the unique values.
df['TARIFFPOINTS'].unique()

array([ 80,  96,   0,  92, 156, 104,  86, 168, 112,  64, 182,  94,  88,
       116, 136, 125,  72, 144, 158, 128, 152, 160,  90, 100, 120, 132,
       118, 108,  24, 114, 102, 146, 124, 110, 140])

In [ ]:
# View the unique values.
df['GREATSTARTACCESS'].unique()

array(['Other students', 'Other low income students',
       'Great Start / Access recipient'], dtype=object)

In [ ]:
# View the unique values.
df['STATEMARKERLABEL'].unique()

array(['State school leaver', 'Unknown', 'Other school leaver'],
      dtype=object)

In [ ]:
# View the unique values.
df['MABSEQ'].unique()

array([1, 2, 3])

In [ ]:
# View the unique values.
df['ASSTYPENAME'].unique()

array(['Coursework', 'Examination - closed book', 'Essay', 'Presentation',
       'In-Class Test/Assignment non exam conditions'], dtype=object)

In [ ]:
# View the unique values.
df['ASSPERC'].unique()

array([0.5, 0.4, 0.6, 0.2, 0.8, 0.3])

In [ ]:
# View the unique values.
df['HASMC'].unique()

array([0, 1])

In [ ]:
# View the unique values.
df['ACCEPTEDMC'].unique()

array([0, 1])

In [ ]:
# Create a box plot for age.
Age_fig = px.box(df, x='AGEONENTRY')
Age_fig.show()

In [ ]:
# create a function to identify outliers in age.
def find_outliers_IQR(df):

  q1=df.quantile(0.25)

  q3=df.quantile(0.75)

  IQR=q3-q1

  outliers = df[((df<(q1-1.5*IQR))|(df>(q3+1.5*IQR)))]

  return outliers

In [ ]:
# Truncate.
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 150)